# Generated by Django 3.2.12 on 2022-04-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ip_addr',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
