# Generated by Django 3.2.12 on 2022-04-19 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('identification_no', models.CharField(max_length=100)),
                ('contact_no', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, default='', null=True, upload_to='visitors')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=12, unique=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_checkin', models.BooleanField(default=False)),
                ('is_approved', models.PositiveSmallIntegerField(choices=[(3, 'Not Approved'), (1, 'Pending Approval'), (2, 'Approved')], default=2, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='visitors/qr')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refs_tenant_visitor', to='accounts.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('identification_no', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, default='', null=True, upload_to='staffs')),
                ('email', models.EmailField(max_length=50, null=True, unique=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=12, unique=True)),
                ('is_approved', models.PositiveSmallIntegerField(choices=[(3, 'Not Approved'), (1, 'Pending Approval'), (2, 'Approved')], default=1, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('qr_image', models.ImageField(null=True, upload_to='staffs/qr')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refs_tenant_staff', to='accounts.tenant')),
            ],
        ),
    ]
