# Generated by Django 3.2.12 on 2022-06-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_registration', '0003_auto_20220421_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='employee_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='is_approved',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Not Approved'), (1, 'Pending Approval'), (2, 'Approved')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='is_approved',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Not Approved'), (1, 'Pending Approval'), (2, 'Approved')], default=2, null=True),
        ),
    ]
