# Generated by Django 3.2.12 on 2022-11-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_registration', '0008_alter_staff_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='', null=True, upload_to='validated_photo')),
                ('code', models.CharField(blank=True, max_length=12, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='staff',
            name='is_approved',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending Approval'), (3, 'Not Approved'), (2, 'Approved')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='is_approved',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending Approval'), (3, 'Not Approved'), (2, 'Approved')], default=2, null=True),
        ),
    ]
